- name: Create dev group
  group: name=dev gid=1000

- name: Create dev user
  user: name=dev
    uid=1000
    home=/home/dev
    group=dev
    groups=dev,users
    shell=/bin/zsh

- name: Fix owner
  command: chown dev.dev -R /home/dev

- name: Sudo rights for all
  lineinfile: 
    'dest=/etc/sudoers create=yes state=present regexp="sudo ALL"
    line="%sudo ALL=(ALL) NOPASSWD: ALL"'