- name: Create dev group
  group: name=dev gid=1000

- name: Create dev user
  user: name=dev
    uid=1000
    home=/home/dev
    group=dev
    shell=/bin/zsh

- name: Create shared directory
  file: path=/var/shared owner=dev group=dev mode=0755 state=directory

- name: Create directory placeholder (need by docker volume)
  file: path=/var/shared/placeholder owner=dev group=dev state=touch

- name: Get dot files
  command: git clone {{ dotfiles_git }} /home/dev/.dotfiles

- name: Link files from the shared directory
  file: src=/var/shared/.ssh dest=/home/dev/.ssh state=link force=yes
  file: src=/var/shared/.gitconfig dest=/home/dev/.gitconfig state=link force=yes
  file: src=/var/shared/src dest=/home/dev/src state=link force=yes

- name: Fix owner
  command: chown dev.dev -R /home/dev

